### ISSUE TITLE
ansible 을 사용하여 자동화 구축하기

### ISSUE THREAD

**Issue by kwonslog** [kwonslog/how-to-use-docker#10]
### ansible 로 자동화 가능 한 작업들...
- nginx 의 설정 파일을 동적으로 변경 후 리로드 가능
- 원격 서버에 젠킨스 설치
- 도커 컨테이너 실행 등...
> ansible 을 이용하여 수작업 또는 반복적인 작업을 미리 정의해 두고 필요할때 실행하여 인프라 구축에 편의성을 준다.

### 그래서?
- 도커를 사용하여 쉽게 테스트 환경을 구축 했다. 물론 도커 자체를 설치하고 설정하는 부분은 직접 수작업으로 진행 했다.
- 그런데 ansible 을 사용하면 이 과정마저 자동화 할 수 있다.

### TODO
- [ ] AWS EC2 인스턴스에 도커 및 도커 컴포즈 설치 자동화
- [ ] 로컬 프로젝트를 1.빌드  2.원격 서버에 업로드 3. 실행 자동화
- [ ] 젠킨스 도커 컨테이너로 설치 자동화
